### ISSUE TITLE
What do you mean by "outdated"?

### ISSUE THREAD

**Issue by Willytor** [Goncholito/isaacscript2#2]
care to elaborate? has development stopped? if so, why ?

**Comment by Goncholito** [comment]
Isaacscript 2 has moved into an organization https://github.com/IsaacScript-2/IsaacScript-2.
Btw, glad to see people are still interested in this project lol.

**Comment by Willytor** [comment]
ah, i see. i was checking out this project cause isaacscript as a concept is cool but in execution has a lot of problems. hope you can make the most of it

**Comment by Goncholito** [comment]
you should check again the page (this website and project itself is pretty much a joke, but if you like isaacscript as a concept, check this https://github.com/maya-bee/isaac-helper)

**Comment by Willytor** [comment]
oh
